# Generated by Django 4.1.6 on 2023-06-19 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_vote_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choice',
            new_name='vote_choice',
        ),
    ]
