# Generated by Django 4.1.6 on 2023-06-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_max_select_vote_max_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote_choice',
            name='description',
        ),
    ]
