# Generated by Django 4.1.6 on 2023-06-19 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_vote_choice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='createUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.adminuser'),
        ),
        migrations.AlterField(
            model_name='vote_choice',
            name='vote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.vote'),
        ),
    ]
