# Generated by Django 4.1.6 on 2023-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_rename_vote_id_vote_choice_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='vote_choice',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
